trigger:
- master
- main

pool:
  vmImage: ubuntu-latest


resources:
  repositories:
  - repository: pipelineTemplates
    type: git
    name: pipelineTemplates

jobs:
- template: gitversion/tag.yml@pipelineTemplates